#!/bin/sh

# ssh variables to yank
SSHV="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

# where to put the output script
DESTDIR=$HOME/tmp

# grab each variable name and format it as an export statement
for x in ${SSHV} ; do
    (eval echo $x=\$$x) | sed  's/=/="/
                                s/$/"/
                                s/^/export /'
done 1>$DESTDIR/fixssh
